{
 'ruleCategory': 
                 {
                  '': 'Category', 
                  'Consumption': '10', 
                  'Category': '', 
                  'Competition': '1', 
                  '6': 'Performance', 
                  'Performance': '6', 
                  '0': 'Training', 
                  '10': 'Consumption', 
                  'Tools for daily use': '9', 
                  'Guidance': '5', 
                  '2': 'Counter', 
                  '7': 'Target / Goal', 
                  'Fun': '4', 
                  'Counter': '2', 
                  '1': 'Competition', 
                  'Estimate': '3', 
                  'Environmental': '8', 
                  '8': 'Environmental', 
                  '3': 'Estimate', 
                  'Target / Goal': '7', 
                  '9': 'Tools for daily use', 
                  '4': 'Fun', 
                  '5': 'Guidance', 
                  'Training': '0'
                 }, 
 'sorting': 
            {
             'My Apps': 't1', 
             'Latest': '5', 
             'Most liked': '6', 
             't1': 'My Apps', 
             'Most used': '10', 
             '10': 'Most used', 
             'Suunto Apps': '15', 
             '15': 'Suunto Apps', 
             '6': 'Most liked', 
             '5': 'Latest'
            }, 
 'activity': 
             {
              '97': 'Fishing', 
              'Standup paddling (SUP)': '89', 
              'Soccer / football': '25', 
              '24': 'Basketball', 
              '74': 'Mountaineering', 
              'Cycling': '4', 
              'Racquet ball': '36', 
              '33': 'Tennis', 
              '1': 'Select', 
              'Cheerleading': '30', 
              'Cross-country skiing': '22', 
              'Canoeing': '72', 
              '84': 'Nordic walking', 
              'Softball': '29', 
              '80': 'Telemark skiing', 
              'Boxing': '39', 
              '12': 'Walking', 
              '10': 'Yoga / pilates', 
              '96': 'Hiking', 
              '16': 'Climbing', 
              'Snowboarding': '21', 
              'Golf': '66', 
              'Alpine skiing': '20', 
              '81': 'Track and field', 
              'Cricket': '63', 
              'Walking': '12', 
              'Rowing': '15', 
              'Bowling': '62', 
              'Fishing': '97', 
              'Indoor cycling': '17', 
              'Baseball': '31', 
              'Roller skiing': '88', 
              'Ski touring': '78', 
              '17': 'Indoor cycling', 
              'Martial arts': '38', 
              '85': 'Snow shoeing', 
              '34': 'Badminton', 
              '58': 'Obstacle racing', 
              'Squash': '37', 
              'Frisbee': '94', 
              '76': 'Rugby', 
              '92': 'Paragliding', 
              '62': 'Bowling', 
              '18': 'Circuit training', 
              '69': 'Horseback riding', 
              '37': 'Squash', 
              '3': 'Running', 
              '82': 'Trail running', 
              '35': 'Table tennis', 
              'Pool swimming': '6', 
              '78': 'Ski touring', 
              'Indoor training': '95', 
              '11': 'Trekking', 
              '22': 'Cross-country skiing', 
              '94': 'Frisbee', 
              '65': 'Dancing', 
              '15': 'Rowing', 
              'Kitesurfing/Kiting': '91', 
              '5': 'Mountain biking', 
              '2': 'Multisport', 
              '29': 'Softball', 
              '26': 'Ice hockey', 
              '31': 'Baseball', 
              '67': 'Gymnastics', 
              'American football': '28', 
              '71': 'Indoor rowing', 
              'Weight training': '23', 
              'Running': '3', 
              'Tennis': '33', 
              'Triathlon': '19', 
              'Snow shoeing': '85', 
              '73': 'Motorsports', 
              'Telemark skiing': '80', 
              '86': 'Windsurfing/Surfing', 
              '79': 'Stretching', 
              'Motorsports': '73', 
              'Horseback riding': '69', 
              'Badminton': '34', 
              '83': 'Openwater swimming', 
              'Rugby': '76', 
              'Windsurfing/Surfing': '86', 
              'Circuit training': '18', 
              '99': 'Transition', 
              'Kettlebell': '87', 
              'Handball': '68', 
              'Paragliding': '92', 
              'Sailing': '13', 
              '6': 'Pool swimming', 
              'CrossFit': '90', 
              'Ice skating': '70', 
              'Stretching': '79', 
              '39': 'Boxing', 
              '90': 'CrossFit', 
              'Yoga / pilates': '10', 
              '72': 'Canoeing', 
              'Ice hockey': '26', 
              '36': 'Racquet ball', 
              '87': 'Kettlebell', 
              'Orienteering': '75', 
              '21': 'Snowboarding', 
              '66': 'Golf', 
              'Hiking': '96', 
              '4': 'Cycling', 
              '28': 'American football', 
              '38': 'Martial arts', 
              'Floorball': '40', 
              'Table tennis': '35', 
              'Select': '1', 
              '8': 'Roller skating', 
              '14': 'Kayaking', 
              'Openwater swimming': '83', 
              '95': 'Indoor training', 
              'Crosstrainer': '64', 
              'Climbing': '16', 
              'Obstacle racing': '58', 
              'Basketball': '24', 
              '98': 'Hunting', 
              'Mountain biking': '5', 
              '27': 'Volleyball', 
              'Volleyball': '27', 
              'Gymnastics': '67', 
              '75': 'Orienteering', 
              'Treadmill': '93', 
              '25': 'Soccer / football', 
              '30': 'Cheerleading', 
              'Trail running': '82', 
              '23': 'Weight training', 
              '70': 'Ice skating', 
              'Nordic walking': '84', 
              '61': 'Adventure racing', 
              'Dancing': '65', 
              '63': 'Cricket', 
              '93': 'Treadmill', 
              'Roller skating': '8', 
              '89': 'Standup paddling (SUP)', 
              'Adventure racing': '61', 
              'Transition': '99', 
              'Aerobics': '9', 
              '13': 'Sailing', 
              '19': 'Triathlon', 
              'Kayaking': '14', 
              'Trekking': '11', 
              'Indoor rowing': '71', 
              'Mountaineering': '74', 
              'Multisport': '2', 
              '91': 'Kitesurfing/Kiting', 
              '68': 'Handball', 
              '40': 'Floorball', 
              '9': 'Aerobics', 
              '20': 'Alpine skiing', 
              '88': 'Roller skiing', 
              '64': 'Crosstrainer', 
              'Hunting': '98', 
              'Track and field': '81'
             }
}

